add: #21pdf-download function
c3-kotatsuneko/frontend pull request #22
Opened 2024-08-05 13:34 UTC by Sea10wood

2024-08-05 14:26 UTC, yuki6ra commented on src/components/features/welcome/DownloadButton/index.module.css
> +  }
ちっさいんですけど、`npm run format`してからpushしてくれると嬉しいです...

2024-08-06 12:37 UTC, Sea10wood commented on src/components/features/welcome/DownloadButton/index.module.css
> +  }
修正しました！

2024-08-07 06:38 UTC, powaaaaa approved these changes

2024-08-17 03:20 UTC, K-Kizuku requested changes

2024-08-17 03:20 UTC, K-Kizuku commented on src/utils/downloads.ts
> +		blob: new URL("../../public/marker/marker_file.pdf", import.meta.url).href,
```suggestion
		blob: new URL("/marker/marker_file.pdf", import.meta.url).href,
```
これでいけるくない？
(publicからインポートすることは基本ないと思ってもらえると)

2024-08-17 04:11 UTC, Sea10wood commented on src/utils/downloads.ts
> +		blob: new URL("../../public/marker/marker_file.pdf", import.meta.url).href,
`blob: new URL("/marker/marker_file.pdf", import.meta.url).href,`

修正しました！

2024-08-17 04:12 UTC, merged