Marker scan
c3-kotatsuneko/frontend pull request #36
Opened 2024-08-15 13:50 UTC by Sea10wood

2024-08-15 14:00 UTC, K-Kizuku requested changes

2024-08-15 14:00 UTC, K-Kizuku commented on src/components/features/scan/index.tsx
> +                    <div className={styles["marker-frame"]}></div>
```suggestion
                    <div className={styles["marker-frame"]} />
```

2024-08-15 14:00 UTC, K-Kizuku commented on src/components/features/scan/index.tsx
> +                    <video ref={videoRef} autoPlay></video>
```suggestion
                    <video ref={videoRef} autoPlay />
```
こうやって書けば、このbiome-ignoreいらなくない？
  {/* biome-ignore lint/style/useSelfClosingElements: <explanation> */}

2024-08-15 14:00 UTC, K-Kizuku commented on src/components/features/scan/index.module.css
> +video {
`.video`みたいにして、スコープをできるだけ小さくしてもらえると事故が少なくなるので助かる。

2024-08-15 14:00 UTC, K-Kizuku commented on src/components/features/scan/index.tsx
> +            if (isMarkerDetected) {
ここの処理は本当にこれで合ってる？？？
このif文がfalseを受けることはないと思うんだけど

2024-09-02 17:44 UTC, Semi-koron commented
ar.jsが動作しているときはイベントリスナーでのマーカー検知が可能なので下記のようなアプローチができるかもしれません。

https://github.com/c3-kotatsuneko/frontend/commit/eb847f01ebbb7eb3b620b72261e20d8b5c3e3e77#diff-ef1b6c92058ae449105477359f31d90053902d5a1347b80d7d703d5edfce317bR25-R34

2024-09-04 05:57 UTC, merged