lintぼくめつ！
c3-kotatsuneko/frontend pull request #39
Opened 2024-08-17 04:47 UTC by powaaaaa

closed #20

2024-08-17 07:55 UTC, K-Kizuku requested changes
挙動が変わったならどう変わったのかも書いといてもらえると
原因がわかるならそれも
原因わからんけどなんか変わったみたいな感じであれば、下手に修正せずにbiome-ignoreとかで対応するようにしてください

2024-08-17 07:55 UTC, K-Kizuku commented on src/pages/PlayTimeAttack/index.tsx
> +		const cleanUp = () => {
これは根本的な解決になっていないので、マージしたいのであれば
`//TODO: 無限レンダリングを直す。これは無限レンダリングにより生成される要素を一時的に削除している`
みたいな感じでコメントつけといてもらえると

2024-08-17 07:55 UTC, K-Kizuku commented on src/pages/PlayTimeAttack/index.tsx
> +		// TODO: クリアしたらrankingページに遷移する?
コメントを疑問形で書かないでください
別でちゃんとコミュニケーションをとって確定事項をコード内にコメントで残すようにしてください

2024-08-17 07:55 UTC, K-Kizuku commented on src/pages/PlayTimeAttack/hooks/useCountTimer.ts
> +export const useCountTimer = (time: number, setTime: (arg: number) => void) => {
このフックは絶妙にキモい
hooks内で状態を保つようにしてそれをexportする方が綺麗だと思います

2024-08-21 11:08 UTC, powaaaaa commented on src/pages/PlayTimeAttack/index.tsx
> +		// TODO: クリアしたらrankingページに遷移する?
なんでこれ書いたか忘れたので消します🤢

2024-08-25 07:44 UTC, powaaaaa commented
- play時に小さいカメラが1つだったのが、小さいカメラ1つと画面全体のカメラ1つの2つ現れる(video要素が1個増えてた)
- 画面全体の方のカメラが少しずつ拡大されてる

差異はこれかなあ　どこが具体的に原因かわからんのでセミコロンくんにみてもらいたい気持ち...
あと無限レンダリングを消したいuseEffect, Timerとか他の要素も消しちゃってたみたいでうまくいかないので無限レンダリングが解消されることを願って削除します...

2024-09-03 06:01 UTC, powaaaaa commented
## develop取り込んだのでこのPRの内容はこれだけになりました
- aframeをuninstall
- timerの処理を編集

2024-09-03 06:53 UTC, Semi-koron approved these changes
クリーンアップ関数も実装されてる事も確認
問題ないと思います。

2024-09-03 06:54 UTC, merged