#47/countdown before game
c3-kotatsuneko/frontend pull request #48
Opened 2024-09-04 08:29 UTC by powaaaaa

2024-09-05 10:43 UTC, Semi-koron approved these changes
websocket周りわからなくてすいません

2024-09-05 10:43 UTC, Semi-koron commented on src/components/features/play/StartCountdown/index.module.css
こんな書き方あるの知らなかった！
勉強になります😮

2024-09-05 10:43 UTC, Semi-koron commented on src/pages/AR/index.tsx
すいません僕が書いたところが何か悪さしたっぽいですね...😥

2024-09-05 11:27 UTC, K-Kizuku requested changes

2024-09-05 11:27 UTC, K-Kizuku commented on src/pages/PlayTimeAttack/hooks/index.ts
> +	const { eventSend } = useSocketRefStore();
```suggestion
	const  eventSend  = useSocketRefStore((state)=>state.eventSend);
```
https://zustand.docs.pmnd.rs/guides/auto-generating-selectors
セレクタを使って書くことが公式からも推奨されているので、その書き方でお願いします

2024-09-05 11:27 UTC, K-Kizuku commented on src/store/useSocketRefStore.ts
> +				// get().eventSend({
ここのコメントはもう削除しちゃってください

2024-09-05 11:27 UTC, K-Kizuku commented on src/pages/PlayTimeAttack/index.tsx
> +const gameDuration = 11;
これをグローバルに定義する必要はありますか？

2024-09-06 06:08 UTC, powaaaaa commented on src/pages/PlayTimeAttack/index.tsx
> +const gameDuration = 11;
ない！消します

2024-09-07 03:52 UTC, merged